#! /bin/bash

#sensors | grep -i id | awk '{print $4 " °C"}' | cut -c 2,3,4,5,6,7,8,9

commandA () { sensors | grep -i id | awk '{print $4 " °C"}' | cut -c 2,3,4,5,6,7,8,9; }
commandB () { echo "Temp"; }

 x="$(commandA)$(commandB)"
 
 echo "$x"
